version: '3.8'

services:
  mysql:
    container_name: "web_calendar_mysql"
    image: "mysql:8.0.32"
    restart: always
    ports:
      - "3312:3306"
    expose:
      - "3312"
    volumes:
      - db_calendar:/data
    environment:
      MYSQL_DATABASE: webcalendar
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass1
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_calendar: